cuadrados_medios = ('Xo', 'Max')
productos_medios = ('Xo', 'X1', 'Max')
multiplicador_constante = ('Xo', 'a', 'Max')
gen_congruencial_mixto = ('Xo', 'a', 'c', 'm', 'Max')
gen_congruencial_multiplicativo = ('Xo', 'a', 'm')
gen_congruencial_cuadratico = ('Xo', 'a', 'b', 'c', 'm')
gen_congruencial_blum_blum_shub = ('Xo', 'a', 'b', 'Max')

tabla_cuadrados_medios = ('n', 'Xo', 'X*X', 'Xn+1', 'ri')
tabla_productos_medios = ('n', 'Xo', 'X1', 'Xo*X1', 'Xn+1', 'ri')
tabla_multiplicador_constante = ('n', 'a', 'X', 'a*X', 'Xn+1', 'ri')
tabla_congruencial_mixto = ('n', 'Xo', 'a*Xn', 'a*Xn+c', 'Xn+1', 'Un')
tabla_congruencial_multiplicativo = ('n', 'Xo', 'a*Xn', 'Xn+1', 'Un')
tabla_congruencial_multiplicativo_binario = ('n', 'Xn')
tabla_congruencial_cuadratico = ('n', 'Xn', 'ri')
tabla_congruencial_blum_blum_shub = ('n', 'Xn', 'ri')
